apiVersion: v1
kind: Service
metadata:
  name: tomcat-member-service
  namespace: member-service
  labels:
    app: backend-member
spec:
  type: ClusterIP # ?´ë? ?„ìš©
  selector:
    app: backend-member
  ports:
    - protocol: TCP
      port: 8080       # ?œë¹„???‘ì† ?¬íŠ¸
      targetPort: 8080 # ì»¨í…Œ?´ë„ˆ ?¬íŠ¸
