apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: web-proxy
  labels:
    app: frontend-proxy
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
         app: frontend-proxy
    spec:
      # ▼▼▼▼ Secret 추가 ▼▼▼▼
      imagePullSecrets:
        - name: ecr-cred-nginx
      # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - frontend-proxy
                topologyKey: "kubernetes.io/hostname"

      containers:
        - name: nginx-proxy-container
          image: 820313036770.dkr.ecr.ap-northeast-2.amazonaws.com/web-proxy:v1.0
          imagePullPolicy: Always
          
          ports:
            - containerPort: 80
          
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"

          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
