FROM alpine:3.21
  
ARG CONF_FILE

# nginx 설치 + 필수 설정
RUN apk add --no-cache nginx && \
    mkdir -p /run/nginx /var/lib/nginx/logs /var/tmp/nginx

COPY ${CONF_FILE} /etc/nginx/http.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
