apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: member-ingress
  namespace: member-service
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # ê·¸ë£¹ ?´ë¦„??ê°™ê²Œ ?¤ì •?˜ë©´ ?˜ë‚˜??ALBë¡??©ì³ì§‘ë‹ˆ??
    alb.ingress.kubernetes.io/group.name: "streets-app-group"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:745173969277:certificate/7bcf3aa1-d03e-4353-ab0b-8bab9c84cb99
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ingressClassName: alb
  rules:
    - host: "12-streets.store"
      http:
        paths:
          # 1. ë¡œê·¸??ê´€???”ì²­?€ ë¬´ì¡°ê±????œë¹„?¤ë¡œ! (ì¶”ê?)
          - path: /login.do
            pathType: Exact
            backend:
              service:
                name: tomcat-member-service
                port:
                  number: 8080
          # 2. JSP ?Œì¼?¤ë„ ???œë¹„?¤ë¡œ! (ì¶”ê?)
          - path: /index.jsp
            pathType: Exact
            backend:
              service:
                name: tomcat-member-service
                port:
                  number: 8080
          # 3. ?˜ë¨¸ì§€??ê¸°ë³¸ ê²½ë¡œ
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tomcat-member-service
                port:
                  number: 8080
