apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-board-deploy
  namespace: board-service
  labels:
    app: backend-board
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: backend-board
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: backend-board
    spec:
      imagePullSecrets:
        - name: ecr-cred-board

      containers:
        - name: tomcat-board-container
          image: 745173969277.dkr.ecr.ap-northeast-2.amazonaws.com/board-service:0c093e8cc404b3533b151671e7f726a8c42c0d8c
          imagePullPolicy: Always
          
          ports:
            - containerPort: 8080
          
          env:
            # 1. 값 전체를 싱글 쿼터(')로 감싸서 쉘 해석을 원천 차단합니다.
            - name: JAVA_OPTS
              value: '-Ddb.url=jdbc:mysql://172.20.252.50:3306/boarddb -Ddb.user=rapa -Ddb.password=1234'
            
            # 2. 혹시 모르니 개별 환경 변수도 가장 단순한 형태로 박습니다.
            - name: DB_URL
              value: "jdbc:mysql://172.20.252.50:3306/boarddb"
            - name: DB_USER
              value: "rapa"
            - name: DB_PASSWORD
              value: "1234"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
