apiVersion: v1
kind: Secret
metadata:
  name: tomcat-board-secret
  namespace: tomcat-board
  labels:
    app: tomcat-board
type: Opaque
stringData:
  # 실제 DB 접속 정보 (Member와 동일하다면 그대로 사용)
  DB_URL: "jdbc:mysql://10.0.2.3:3306/streets?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
  DB_USER: "rapa"
  DB_PASSWORD: "1234"
