apiVersion: v1
kind: Secret
metadata:
  name: tomcat-member-secret
  namespace: tomcat-member
  labels:
    app: tomcat-member
type: Opaque
stringData:
  # DB 접속 정보 확인 필요
  DB_URL: "jdbc:mysql://10.0.2.3:3306/streets?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
  DB_USER: "rapa"
  DB_PASSWORD: "1234"
