/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2025-11-05 09:24:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    // 1. 세션에서 로그인 정보 확인
    String username = (String) session.getAttribute("loggedInUser");

    // 2. 로그인 실패 시 전달된 에러 파라미터 확인
    String loginError = request.getParameter("error");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>메인 페이지</title>\n");
      out.write("    <style>\n");
      out.write("        /* 간단한 2단 레이아웃 */\n");
      out.write("        #container { display: flex; }\n");
      out.write("        #content { flex: 3; padding: 10px; }\n");
      out.write("        #sidebar { flex: 1; padding: 10px; border-left: 1px solid #ccc; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div id=\"container\">\n");
      out.write("        <div id=\"content\">\n");
      out.write("            <h1>E-commerce 12th Street</h1>\n");
      out.write("            <h2>게시판 목록</h2>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"mypage.do\">마이 페이지</a><br></li>\n");
      out.write("                <li><a href=\"board.jsp?id=2\">상품 문의</a> (아직 구현 안 됨)</li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"sidebar\">\n");
      out.write("            ");

                // 3. 세션 정보(username)에 따라 분기
                if (username == null) {
                    // [A] 로그아웃 상태: 로그인 폼 표시
            
      out.write("\n");
      out.write("                <h3>로그인</h3>\n");
      out.write("                <form action=\"login.do\" method=\"POST\">\n");
      out.write("                    <div>\n");
      out.write("                        <label>ID:</label>\n");
      out.write("                        <input type=\"text\" name=\"username\" style=\"width: 90%;\">\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <label>PW:</label>\n");
      out.write("                        <input type=\"password\" name=\"password\" style=\"width: 90%;\">\n");
      out.write("                    </div>\n");
      out.write("                    <button type=\"submit\" style=\"width: 100%; margin-top: 5px;\">로그인</button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                ");

                    // 4. 로그인 실패 시 에러 메시지 표시
                    if ("1".equals(loginError)) {
                
      out.write("\n");
      out.write("                    <p style=\"color:red; font-size: 0.9em;\">아이디/비밀번호가 틀렸습니다.</p>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("                \n");
      out.write("                <hr>\n");
      out.write("                <a href=\"register.jsp\">회원가입 하러가기</a>\n");
      out.write("            \n");
      out.write("            ");

                } else {
                    // [B] 로그인 상태: 환영 메시지 표시
            
      out.write("\n");
      out.write("                <h3>내 정보</h3>\n");
      out.write("                <p><strong>");
      out.print( username );
      out.write("</strong> 님, 환영합니다!</p>\n");
      out.write("                <a href=\"mypage.do\">마이 페이지</a><br>\n");
      out.write("                <a href=\"logout.do\">로그아웃</a>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
